### ISSUE TITLE
Feature Request: Possibility to also dump previous track into separate txt file.

### ISSUE THREAD

**Issue by RadioWavetable** [e1miran/Now-Playing-Serato#10]
Hi,

I wonder whether it's not too much to ask for having another feature. 

As your app is now scraping the Serato live page for new info on the current track, would it be possible to dump the previous track info into a separate txt file? (applying the same option you have set for the current track info)

This could be a toggle option to enable/disable. 

Looking forward to your response.

Thanks in advance for looking into the possibilities!

Kind regards

**Comment by e1miran** [comment]
This is possible and has added value.  I'll put it on the list for future update.

**Comment by speedyb22** [comment]
Would it be possible to keep a full history in the secondary file? This way users could have the full tracklist for the set/stream/event showing on the screen in a chat-like fashion, and also have record of the tracks played if not recorded by any other means.

I tried something using PowerShell and Get-Content -Wait, but it doesn't seem to work quite as expected.

**Comment by e1miran** [comment]
> Would it be possible to keep a full history in the secondary file? 

It's possible.  But, not sure how it would affect something like OBS grabbing the text. Does OBS display all the text in a file or just the first line? If it's the former, then this would defeat the original requestor's purpose of being able to display the current and last played songs. That would mean having to create a third text file for your intent. While I like the idea and see its merit, I'd have to think about if I want to further complicate things this way.

**Comment by speedyb22** [comment]
Default behaviour is to display the whole text file. However there's a "Chatlog Mode" tick-box, which lets you select how many lines you wish to display; setting this to "1" will only display the latest line in the file.

**Comment by e1miran** [comment]
This repo is no longer being maintained or updated. Please visit the forked repo that has wonderfully built on and added to Now Playing: https://github.com/aw-was-here/Now-Playing-Serato
