### ISSUE TITLE
Feature Request: Simple formatting options for the txt dumped in the txt file

### ISSUE THREAD

**Issue by RadioWavetable** [e1miran/Now-Playing-Serato#11]
Hi,

I wonder if I can request one last feature request to look into.

Would it be possible to have the option to either make the dumped text all upper or all lower case?
I would be nice to have the option to choose whether you want the txt:
- ALL UPPER CASE
- all lower case
- Capitalised First Letter

I hope this is something simple to implement. 
Looking forward to your response on this one.

Kind regards.

**Comment by e1miran** [comment]
This is an easy ask.  I'll put in on the list for future update.

**Comment by e1miran** [comment]
This repo is no longer being maintained or updated. Please visit the forked repo that has wonderfully built on and added to Now Playing: https://github.com/aw-was-here/Now-Playing-Serato
