### ISSUE TITLE
Track info not being retrieved

### ISSUE THREAD

**Issue by djreggieward** [e1miran/Now-Playing-Serato#12]
My youtube name is Legacy907 Studios, my name is Reggie, you responded a few times to me on DJ Lazy Eyes post on youtube.  I"m not sure what I'm doing wrong, I've got it setup to read the history not playlist, and pointing to a text file.  And in OBS it's pointing to that same text file.

**Comment by djreggieward** [comment]
So if I open up the text file and type something in I do see it in OBS.  I do have your program point to my _serato_ folder on my computers hard drive, and not my external drive, and as I mentioned earlier your program is pointing to the text file

**Comment by e1miran** [comment]
Hi Reggie.  Can you take and post a screenshot of the Settings page for my tool, please.  Also, you had it working with the Live Playlist before, correct?  It's the same text file, right?

**Comment by djreggieward** [comment]
using the older windows version through wine, I was.  I have not tried 
the remote version on my mac.

The World Famous DJ Reggie Ward KNBA 90.3 Core DJ's World Wide Legacy907
Studios www.facebook.com/djreggieward
https://www.facebook.com/fridaynightmix www.coredjs.com/djreggieward
www.djreggieward.com

**Comment by e1miran** [comment]
Ok. Please post the screenshot of the settings when you can.  In the meantime, let's make sure your text file is using the correct encoding. Double check that it's saved as plain text.  Also, open it in TextEdit and in its preferences, make sure that the open and save encoding is UTF-8 (see the attached).
![Screen Shot 2020-11-12 at 9 23 07 PM](https://user-images.githubusercontent.com/41588119/99020948-90524980-252d-11eb-872f-c1ee63f2a8df.png)

**Comment by djreggieward** [comment]
Did you not getting the screen shot I sent you?

The World Famous DJ Reggie Ward KNBA 90.3 Core DJ's World Wide Legacy907
Studios www.facebook.com/djreggieward
https://www.facebook.com/fridaynightmix www.coredjs.com/djreggieward
www.djreggieward.com

**Comment by djreggieward** [comment]
Hey so by changing the settings for the text file like you suggested 
resolved this issue, thank you!

The World Famous DJ Reggie Ward KNBA 90.3 Core DJ's World Wide Legacy907
Studios www.facebook.com/djreggieward
https://www.facebook.com/fridaynightmix www.coredjs.com/djreggieward
www.djreggieward.com

**Comment by e1miran** [comment]
Awesome.  Enjoy!

**Comment by djreggieward** [comment]
Thank you so much
