### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by ThisIsNoahEvans** [e1miran/Now-Playing-Serato#13]
On Apple Silicon (M1 MacBook Pro), the app opens but doesn't show anything. Activity Monitor shows the app as "Not Responding".

Is there a possibility this could be addressed, or not? Thank you in advance 😃

**Comment by e1miran** [comment]
Not anytime soon, I'm afraid. I'll need to wait until the compiler is updated for the new Apple silicon. And even then I won't be able to verify that it works as I'm not planning on buying an Apple silicon based Mac in the immediate future.

**Comment by ThisIsNoahEvans** [comment]
Alright, thank you for the response 👍🏻

**Comment by kyds3k** [comment]
Same problem with a 2019 Macbook Pro, running Big Sur. I KNEW I should have waited!!! Glad this exists though. I may have to swap over to my PC for DJing!

**Comment by e1miran** [comment]
Good to know. That means I'll need to wait until I install Big Sur (not happening yet) before I can attempt to remediate the issue.

**Comment by ThisIsNoahEvans** [comment]
I cloned the repo, opened `SeratoNowPlaying.py` in VS Code, and then ran the program through a Rosetta (Intel x86 emulator) version of Terminal. It all worked perfectly fine and I was able to successfully use it with Serato DJ Pro and OBS.

It's just the .app from GitHub that doesn't work for me. Hope this helps.

(M1 MacBook Pro with Big Sur, by the way.)

**Comment by e1miran** [comment]
This repo is no longer being maintained or updated. Please visit the forked repo that has wonderfully built on and added to Now Playing: https://github.com/aw-was-here/Now-Playing-Serato
