### ISSUE TITLE
Not writing song names to file

### ISSUE THREAD

**Issue by vladdrac6** [e1miran/Now-Playing-Serato#25]
Hello, I started with this awesome app earlier this week using it with Serato live playlists. The app stopped writing to the text file yesterday. I have installed a new copy of the application and have verified that the Serato live playlists are working. I have also verified the text file is the correct format and has write permission.

I am on macOS 10.15.7. 

Thanks for any help :)

**Comment by e1miran** [comment]
This repo is no longer being maintained or updated. Please visit the forked repo that has wonderfully built on and added to Now Playing: https://github.com/aw-was-here/Now-Playing-Serato
