### ISSUE TITLE
Local mode: not writing anything to txt file.

### ISSUE THREAD

**Issue by sgoff** [e1miran/Now-Playing-Serato#32]
I am running Now Playing Serato 1.4.0 (also tried 1.3.0), Serato DJ 2.4.6 (via a Rane 72 mkII) on Windows 10, and Windows Defender Firewall is set up to allow both Serato DJ and Now Playing Serato through the firewall. 

I'm trying to run your application in local mode (with the Serato library specified being the "_Serato_" folder in the "music" directory on my local drive), and when I load tracks in Serato, nothing is written to the specified text file. Additionally, I have Windows system notifications turned on, and there are no notifications made when loading tracks in Serato. 

I tried running in remote mode, as well, but there seems to be a problem with live playlists for me, for which I have opened a support tag with Serato tech support. Not sure if it's relevant, here, but I'll explain, just in case. I have live playlists turned on in Serato prefs, and the "start live playlist" button appears fine. Clicking it shows a progress bar to the right that fills and then I am taken to my Serato.com account, where I click the 'start live playlist" button. This opens my live playlist page on the Serato site, which I set to public by editing details. However, when I load tracks in Serato, the live playlist page on Serato.com does not update. Eventually, when I click the "start live playlist", "start session", or "end session" button in the Serato DJ history panel, the live playlist page on Serato.com will update with the two currently loaded tracks. If I still have Now Playing Serato open and running in remote mode (with all settings needed to enable this set properly), this final update on my Serato.com live playlist page also does not trigger any text to be written to the specified text file. 

Any help you can give in getting this working would be awesome! Thanks so much for taking the time to put together such a handy application :-)

**Comment by e1miran** [comment]
This repo is no longer being maintained or updated. Please visit the forked repo that has wonderfully built on and added to Now Playing: https://github.com/aw-was-here/Now-Playing-Serato
