### ISSUE TITLE
Script Error message on initial execution due to no config.ini

### ISSUE THREAD

**Issue by djreggieward** [e1miran/Now-Playing-Serato#4]
When running the latest version of SeratoNowPLaying ver 1.20 I keep getting Failed to execute error message.  I'm running it on a Windows 10 desktop computer
![Capture](https://user-images.githubusercontent.com/72527839/95392958-239cbd00-08a6-11eb-8042-bff77a66bc6e.PNG)

**Comment by e1miran** [comment]
@djreggieward  Were you able to run it at all?  Or is this occurring on your initial execution of the app?

**Comment by e1miran** [comment]
@djreggieward Download or create a copy of the config.ini file found here: [config.ini](https://github.com/e1miran/Now-Playing-Serato/tree/master/Serato-Now-Playing/bin).  

Place it inside the 'bin' folder within the same directory as the app.  Let me know if you are able to then open it.

**Comment by e1miran** [comment]
@djreggieward Doing some more testing it looks like on first execution when no config.ini file has yet been created, you will need to right click the app icon and select "Run as Administrator".  This allows the app to write the initial config.ini file.    I will update the ReadMe info accordingly.

**Comment by djreggieward** [comment]
I've tried that running as Admin, same error message.  The older version 
works by doing that.  But it takes to long to read the songs in the 
playlist even setting the seconds to 10

The World Famous DJ Reggie Ward KNBA 90.3 Core DJ's World Wide Legacy907
Studios www.facebook.com/djreggieward
https://www.facebook.com/fridaynightmix www.coredjs.com/djreggieward
www.djreggieward.com

**Comment by djreggieward** [comment]
Not able to run it at all

The World Famous DJ Reggie Ward KNBA 90.3 Core DJ's World Wide Legacy907
Studios www.facebook.com/djreggieward
https://www.facebook.com/fridaynightmix www.coredjs.com/djreggieward
www.djreggieward.com

**Comment by djreggieward** [comment]
creating the ini file worked.  The program opens!

The World Famous DJ Reggie Ward KNBA 90.3 Core DJ's World Wide Legacy907
Studios www.facebook.com/djreggieward
https://www.facebook.com/fridaynightmix www.coredjs.com/djreggieward
www.djreggieward.com

**Comment by e1miran** [comment]
> creating the ini file worked. The program opens! 
Great!  I'll remedy this when I get a chance by creating a pre-packaged blank config.ini file instead of having the app create one on the first execution.  

I'm leaving this issue open until I make the change.

**Comment by e1miran** [comment]
@djreggieward Question for you.  Since you were using the previous version, did you simply replace the .exe file with the latest one, or did you unpack the entire latest release which includes the 'bin' folder?  The previous version didn't have a 'bin' folder included. I'm just trying to get a complete picture of the issue.  Thanks.

**Comment by djreggieward** [comment]
Unpack the entire package

**Comment by e1miran** [comment]
Added pre-built config.ini in v1.3.0.  Closing this issue.
