### ISSUE TITLE
Feature Request: Direct send to OBS Text GDI+ Source through websocket

### ISSUE THREAD

**Issue by DachsbauTV** [e1miran/Now-Playing-Serato#45]
Hey hey,

First off: Amazing app!

I was struggling to get the remote option to work, that's why in our last show I detoured to a local txt file which would be synced through our cloud to the OBS PC.
It actually worked quite well, however, I figured it would be a great addition to actually send the text straight to OBS.

This should actually be quite easy through the websockets plugin, which is widely used by companion anyways.
This would be the corresponding API https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#gettextgdiplusproperties

This would allow to send the track info straight over the network to OBS with minimal delay.

**Comment by e1miran** [comment]
This repo is no longer being maintained or updated. Please visit the forked repo that has wonderfully built on and added to Now Playing: https://github.com/aw-was-here/Now-Playing-Serato
